# Generated by Django 5.2.9 on 2026-01-22 07:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_name_tr', models.CharField(max_length=100, null=True)),
                ('city_name_en', models.CharField(max_length=100, null=True)),
                ('city_name_ru', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('region_name_tr', models.CharField(max_length=100, null=True)),
                ('region_name_en', models.CharField(max_length=100, null=True)),
                ('region_name_ru', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_photos')),
                ('role', models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], default='buyer', max_length=20)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('district_name_tr', models.CharField(max_length=100, null=True)),
                ('district_name_en', models.CharField(max_length=100, null=True)),
                ('district_name_ru', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.city')),
                ('city_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.city')),
                ('city_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.city')),
                ('city_tr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_tr', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
                ('description_tr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('commercial property', 'commercial property'), ('room', 'room'), ('plot', 'plot'), ('dacha', 'dacha'), ('parking/garage', 'parking/garage')], max_length=120)),
                ('address', models.CharField(max_length=100)),
                ('address_tr', models.CharField(max_length=100, null=True)),
                ('address_en', models.CharField(max_length=100, null=True)),
                ('address_ru', models.CharField(max_length=100, null=True)),
                ('area', models.DecimalField(decimal_places=1, max_digits=5)),
                ('area_tr', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('area_en', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('area_ru', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('total_floor', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('for finishing', 'for finishing'), ('European-standard renovation', 'European-standard renovation'), ('good', 'good'), ('average', 'average'), ('unfinished', 'unfinished'), ('any', 'any')], default='any', max_length=120)),
                ('documents', models.BooleanField()),
                ('documents_tr', models.BooleanField()),
                ('documents_en', models.BooleanField()),
                ('documents_ru', models.BooleanField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.district')),
                ('district_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.district')),
                ('district_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.district')),
                ('district_tr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.district')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.region')),
                ('region_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region')),
                ('region_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region')),
                ('region_tr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to='property_photos')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house_app.region'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_app.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
