# Generated by Django 5.2.9 on 2026-01-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='house_app.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_en',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_ru',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_tr',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='house_app.region'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='house_app.property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='house_app.property'),
        ),
    ]
