# Generated by Django 5.2.9 on 2026-01-22 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0002_property_city_alter_city_region_alter_city_region_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_date',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
